#%RAML 0.8
---
title: API Resource
baseUri: https://localhost/api/
protocols: [HTTPS]
mediaType: application/json

traits:
  - auth: !include _traits/auth.raml

/users:
  description: User resource.
  get:
    is: [auth: { roles: 'staff' }]
    description: Retrive the list of the users.
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "firstname": "Florent",
                  "lastname": "Terieur",
                  "phone": "+6624582",
                  "roles": [
                    "citizen"
                  ]
                },
                {
                  "id": "54d8ae163fd30364605c81a9",
                  "firstname": "Romain",
                  "lastname": "Terieur",
                  "phone": "+8211332",
                  "roles": [
                    "citizen",
                    "staff"
                  ]
                },
                ...
              ]
  post:
    description: Create a new user.
    body:
      application/json:
        example: |
          {
            "firstname": "Florent",
            "lastname": "Terieur",
            "phone": "+6624582",
            "roles": [
              "citizen"
            ]
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "id": "54d8ae163fd30364605c81a4",
                "firstname": "Florent",
                "lastname": "Terieur",
                "phone": "+6624582",
                "roles": [
                  "citizen"
                ]
              }

  /{id}:
    get:
      is: [auth: {roles: 'any'} ]
      description: Retrieve the details of a specific user.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "firstname": "Romain",
                  "lastname": "Terieur",
                  "phone": "+6624582",
                  "roles": [
                    "citizen"
                  ]
                }
    put:
      is: [auth: {roles: 'staff'} ]
      description: Update the details of a specific user.
      body:
        application/json:
          example: |
            {
              "firstname": "Romain",
              "lastname": "Terieur",
              "phone": "+6624582",
              "roles": [
                "citizen"
              ]
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "firstname": "Romain",
                  "lastname": "Terieur",
                  "phone": "+6624582",
                  "roles": [
                    "citizen"
                  ]
                }
    delete:
      is: [auth: {roles: 'staff'} ]
      description: Delete a specific user.
      responses:
        204:
          body:
/issues:
  description: issues resource.
  get:
    is: [auth: { roles: 'staff' }]
    description: Retrive the list of the issues.
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id" : "5463rasd2321321",
                  "userId": "54d8ae163f8776",
                  "issueTypeId": "e163fd3036",
                  "desc": "Problem on road Morges 21",
                  "date": "2012-12-31",
                  "geoData": {
                  "long": 41.123213,
                  "lat": 7.623453323
                  },
                  "comment":{
                  "author": "2343223sa",
                  "date": "2012-12-24",
                  "content":"Winter is coming"
                  },
                  "tag": "water,fire",
                  "status" : "created"
                },
                {
                  "id" : "5463rasd2321321",
                  "userId": "54d8ae163f8776",
                  "issueTypeId": "e163fd3036",
                  "desc": "Problem on riverside",
                  "date": "2012-12-31",
                  "geoData": {
                  "long": 41.123213,
                  "lat": 7.623453323
                  },
                  "comment":[
                  {
                  "author": "23432sfsa",
                  "date": "2012-12-24",
                  "content":"Winter is coming"
                  },
                  {
                  "author": "23432sfsa",
                  "date": "2012-12-24",
                  "content":"bad dog on the place"
                  }
                  ],
                  "tag": "water,fire",
                  "status" : "in_progress"
                },
                ...
              ]
  post:
    description: Create a new issue.
    body:
      application/json:
        example: |
          {
                "userId": "54d8ae163f8776",
                "issueTypeId": "e163fd3036",
                "desc": "Problem on road Morges 21",
                "date": "2012-12-31",
                "geoData": {
                "long": 41.123213,
                "lat": 7.623453323
                },
                "comment":{
                "author": "23432sfsa",
                "date": "2012-12-24",
                "content":"Winter is coming"
                },
                "tag": "water,fire",
                "status" : "created"
          }
  /{id}:
    get:
      is: [auth: {roles: 'any'} ]
      description: Retrieve the details of a specific issue.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "userId": "54d8ae163f8776",
                  "issueTypeId": "e163fd3036",
                  "desc": "Problem on road Morges 21",
                  "date": "2012-12-31",
                  "geoData": {
                  "long": 41.123213,
                  "lat": 7.623453323
                  },
                  "comment":[
                  {
                  "author": "23432sfsa",
                  "date": "2012-12-24",
                  "content":"Winter is coming"
                  },
                  {
                  "author": "23432sfsa",
                  "date": "2012-12-24",
                  "content":"Winter is coming"
                  }
                  ],
                  "tag": "water,fire",
                  "status" : "created"
                }     
    put:
      is: [auth: {roles: 'staff'} ]
      description: Update the details of a specific issues.
      body:
        application/json:
          example: |
            {
              "userId": "54d8ae163f8776",
              "issueTypeId": "e163fd3036",
              "desc": "Problem on road Morges 21",
              "date": "2012-12-31",
              "geoData": {
              "long": 41.123213,
              "lat": 7.623453323
              },
              "comment":{
              "author": "23432sfsa",
              "date": "2012-12-24",
              "content":"Winter is coming"
              },
              "tag": "water,fire",
              "status" : "created"
                }
    delete:
      is: [auth: {roles: 'staff'} ]
      description: Delete a specific issue.
      responses:
        204:
          body:
  /action:



/issueType:
  description: issueType resource.
  get:
    is: [auth: { roles: 'any' }]
    description: Retrive the list of type of issues.
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Graffiti",
                  "desc": "Graffiti a un endroit non approprie",
                },
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Degat",
                  "desc": "Degat sur la voix public",
                },
                ...
              ]
  post:
    description: Create a new issueType.
    body:
      application/json:
        example: |
          [
                {
                  
                  "name": "Graffiti",
                  "desc": "Graffiti a un endroit non approprie",
                }
          ]
    responses:
      201:
        body:
          application/json:
            example: |
              [
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Graffiti",
                  "desc": "Graffiti a un endroit non approprie",
                }
              ]
  /{id}:
    get:
      is: [auth: {roles: 'any'} ]
      description: Retrieve the details of a specific type of issue.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Romain",
                  "desc": "Terieur",
                }
    put:
      is: [auth: {roles: 'staff'} ]
      description: Update the details of a specific type of issue.
      body:
        application/json:
          example: |
            {
              
              "name": "Terieur",
              "desc": "+6624582",
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Romain",
                  "desc": "Terieur",
                }
    delete:
      is: [auth: {roles: 'staff'} ]
      description: Delete a specific user.
      responses:
        204:
          body:
              





/data:
  description: Data resource.
  /populate:
    post:
      description: Allow to populate random data to have a starting situation.
      responses:
        200:
          body:
